const clean=s=>(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'\"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}};
const platformOf=u=>{const h=host(u);if(h.includes('instagram.com'))return'Instagram';if(h.includes('t.me')||h.includes('telegram'))return'Telegram';if(h.includes('youtube.com')||h.includes('youtu.be'))return'YouTube';if(h.includes('x.com')||h.includes('twitter.com'))return'X';return'Web'};
async function text(url){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(4500)});return r.ok?await r.text():''}catch{return''}}
function rss(xml){return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(m=>{const x=m[1],get=t=>clean(x.match(new RegExp(`<${t}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${t}>`))?.[1]||'');const link=get('link');return{title:get('title'),link,published:get('pubDate')||get('published'),source:get('source')||host(link),description:get('description'),platform:'Web'}}).filter(x=>x.title)}
async function web(q){const t=await text(`https://r.jina.ai/http://www.google.com/search?q=${encodeURIComponent(q)}`),out=[];for(const m of t.matchAll(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g)){const link=m[2];if(host(link).includes('google.com'))continue;out.push({title:clean(m[1]),link,source:host(link),platform:platformOf(link)})}return out.slice(0,50)}
async function news(q){const [g,b]=await Promise.all([text(`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=fa&gl=IR&ceid=IR:fa`),text(`https://www.bing.com/news/search?q=${encodeURIComponent(q)}&format=rss&setlang=fa-ir`)]);return[...rss(g),...rss(b)]}
const domains={Instagram:'site:instagram.com',Telegram:'site:t.me',X:'site:x.com',YouTube:'site:youtube.com',Web:''};
export async function searchConnector(platform,q){const suffix=domains[platform];if(!suffix) return dedupe([...(await web(q)),...(await news(q))]);const qq=`${q} ${suffix}`;return dedupe([...(await web(qq)),...(await news(qq))].map(x=>({...x,platform})));}
function dedupe(items){const m=new Map();for(const x of items){const k=x.link||`${x.platform}|${x.title}|${x.source}`;if(x.title&&!m.has(k))m.set(k,x)}return[...m.values()]}
export const connectorConfig=Object.fromEntries(Object.keys(domains).map(platform=>[platform,{enabled:true,mode:'public-index',queryDomain:domains[platform]||'general-web'}]));