import { useMemo, useState } from "react";
import { Activity, Bell, Download, Hash, LayoutDashboard, MessageCircle, Plus, Search, Settings, TrendingUp, Users, X } from "lucide-react";

const seed=[
 {platform:"Instagram",author:"music_daily",text:"بالاخره جزئیات جدیدی از صحنه منتشر شد.",sentiment:"مثبت",topic:"اخبار برنامه",engagement:1260},
 {platform:"Web",author:"خبرگزاری هنر",text:"برنامه صحنه با حضور صد داور موسیقی به زودی منتشر می‌شود.",sentiment:"مثبت",topic:"صحنه",engagement:842},
 {platform:"Telegram",author:"Music News",text:"صد داور؛ ایده‌ای متفاوت برای یک برنامه موسیقی.",sentiment:"مثبت",topic:"صد داور",engagement:510},
 {platform:"X",author:"@music_user",text:"همه درباره پشت صحنه صحنه صحبت می‌کنند.",sentiment:"منفی",topic:"پشت صحنه",engagement:2180},
 {platform:"Web",author:"رسانه فرهنگی",text:"حضور فرزاد فرزین به عنوان مجری صحنه.",sentiment:"خنثی",topic:"فرزاد فرزین",engagement:390}
];
const nav=[["overview","نمای کلی",LayoutDashboard],["feed","فید منشن‌ها",MessageCircle],["topics","موضوعات",Hash],["accounts","اکانت‌ها",Users],["alerts","هشدارها",Bell]];
function Stat({icon:Icon,label,value,change}){return <div className="stat"><span><Icon size={18}/></span><small>{label}</small><strong>{value}</strong><em>{change}</em></div>}
function Head({title,sub,action}){return <div className="head"><div><h3>{title}</h3><small>{sub}</small></div>{action}</div>}
function Mentions({items}){return <div className="mentions">{items.map((m,i)=><article key={i}><div className="mention-meta"><span>{m.platform}</span><time>امروز</time><i className={m.sentiment}>{m.sentiment}</i></div><strong>{m.author}</strong><p>{m.text}</p><footer><b>#{m.topic}</b><span>{m.engagement.toLocaleString("fa-IR")} تعامل</span></footer></article>)}</div>}
export default function App(){
 const [page,setPage]=useState("overview"),[keyword,setKeyword]=useState("صحنه"),[query,setQuery]=useState(""),[platform,setPlatform]=useState("همه"),[sentiment,setSentiment]=useState("همه"),[modal,setModal]=useState(false),[toast,setToast]=useState("");
 const filtered=useMemo(()=>seed.filter(m=>(platform==="همه"||m.platform===platform)&&(sentiment==="همه"||m.sentiment===sentiment)&&(!query||`${m.author} ${m.text} ${m.topic}`.includes(query))),[query,platform,sentiment]);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(""),2800)};
 const exportCsv=()=>{const rows=["Platform,Author,Text,Sentiment,Topic,Engagement",...filtered.map(m=>[m.platform,m.author,m.text,m.sentiment,m.topic,m.engagement].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+rows.join("\n")],{type:"text/csv"}));a.download=`social-listening-${keyword}.csv`;a.click();notify("CSV آماده شد.")};
 return <div className="app" dir="rtl"><aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><b>Social Listening</b><small>OS / MVP</small></div></div><button className="new-monitor" onClick={()=>setModal(true)}><Plus size={17}/> مانیتور جدید</button><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-foot"><Settings size={16}/> تنظیمات اتصال</div></aside>
 <main className="main"><header className="topbar"><div><small>SOCIAL LISTENING OS</small><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div><div className="monitor-pill"><Hash size={15}/>{keyword}</div></header>
 {page==="overview"&&<><section className="hero"><div><span className="live"><i/> MONITORING</span><h2>نبض گفتگو درباره «{keyword}»</h2><p>داده‌های فعلی نمونه‌اند؛ ساختار محصول برای اتصال به منابع واقعی آماده است.</p></div><button onClick={()=>setModal(true)}><Plus size={16}/> افزودن کلیدواژه</button></section><section className="stats"><Stat icon={MessageCircle} label="منشن‌ها" value="3,842" change="+28.4%"/><Stat icon={Activity} label="تعامل" value="18.6K" change="+17.2%"/><Stat icon={TrendingUp} label="Sentiment مثبت" value="64.8%" change="+8.6%"/><Stat icon={Bell} label="هشدار فعال" value="7" change="3 جدید"/></section><div className="grid"><section className="panel"><Head title="روند گفتگو" sub="۷ روز اخیر"/><div className="fake-chart"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><polyline points="0,180 90,160 180,175 270,115 360,130 450,72 540,94 700,35"/></svg><div className="chart-labels"><span>شنبه</span><span>یکشنبه</span><span>دوشنبه</span><span>سه‌شنبه</span><span>چهارشنبه</span><span>پنجشنبه</span><span>جمعه</span></div></div></section><section className="panel"><Head title="Share of Voice" sub="بر اساس پلتفرم"/><div className="bars">{[["Instagram",42],["Web",28],["Telegram",18],["X",12]].map(x=><div className="bar-row" key={x[0]}><span>{x[0]}</span><div><i style={{width:`${x[1]}%`}}/></div><b>{x[1]}%</b></div>)}</div></section></div><section className="panel"><Head title="آخرین منشن‌ها" sub="داده نمونه / Demo" action={<button className="link" onClick={()=>setPage("feed")}>مشاهده فید</button>}/><Mentions items={seed}/></section></>}
 {page==="feed"&&<section className="panel"><Head title="فید منشن‌ها" sub={`${filtered.length} نتیجه`} action={<button className="export" onClick={exportCsv}><Download size={15}/> CSV</button>}/><div className="filters"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجو در منشن‌ها..."/>{query&&<X size={15} onClick={()=>setQuery("")}/>}</div><select value={platform} onChange={e=>setPlatform(e.target.value)}><option>همه</option><option>Instagram</option><option>Web</option><option>Telegram</option><option>X</option></select><select value={sentiment} onChange={e=>setSentiment(e.target.value)}><option>همه</option><option>مثبت</option><option>خنثی</option><option>منفی</option></select></div><Mentions items={filtered}/></section>}
 {page==="topics"&&<section className="panel"><Head title="موضوعات داغ" sub="بر اساس حجم گفتگو"/><div className="topic-table">{[["صحنه",1240,38],["صد داور",870,27],["فرزاد فرزین",610,19],["حامد جوادزاده",480,14],["پشت صحنه",350,9]].map((x,i)=><div className="topic" key={x[0]}><b>{i+1}</b><strong>{x[0]}</strong><div><i style={{width:`${Math.min(x[1]/14,100)}%`}}/></div><span>{x[1].toLocaleString("fa-IR")}</span><em>+{x[2]}%</em></div>)}</div></section>}
 {page==="accounts"&&<section className="panel"><Head title="اکانت‌ها" sub="حساب‌های اثرگذار در داده نمونه"/><div className="accounts">{seed.map((m,i)=><div key={i}><div className="avatar">{m.author[0]}</div><strong>{m.author}</strong><span>{m.platform}</span><b>{m.engagement.toLocaleString("fa-IR")} تعامل</b></div>)}</div></section>}
 {page==="alerts"&&<section className="panel"><Head title="هشدارها" sub="Rules آماده اتصال به داده واقعی"/><div className="empty"><Bell size={30}/><h3>هشدار هوشمند</h3><p>جهش حجم گفتگو، sentiment منفی و وایرال‌شدن محتوا را می‌توان به‌صورت خودکار مانیتور کرد.</p><button onClick={()=>notify("Rule هشدار ثبت شد.")}>ساخت Rule</button></div></section>}
 </main>{modal&&<div className="modal-backdrop" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h3>مانیتور جدید</h3><p>کلیدواژه یا نام برند</p><input autoFocus value={keyword} onChange={e=>setKeyword(e.target.value)}/><button onClick={()=>{setModal(false);notify(`مانیتور «${keyword}» آماده اتصال شد.`)}}>ساخت مانیتور</button></div></div>}{toast&&<div className="toast">{toast}</div>}</div>
}