import { useState } from 'react';
import { Search, Plus, Download, MessageCircle, Activity, Hash, Bell, Filter } from 'lucide-react';

const nav=[['overview','نمای کلی'],['feed','فید نتایج'],['topics','تاپیک‌ها'],['accounts','منابع'],['alerts','هشدارها']];
const sentimentOf=m=>m.sentiment||((m.title||'').match(/عالی|موفق|برنده|مثبت|خوب/)?'مثبت':(m.title||'').match(/بد|بحران|شکست|حاشیه|انتقاد|منفی/)?'منفی':'خنثی');
const topicOf=m=>m.topic||m.matchedEntities?.[0]||m.source||'عمومی';
function ResultTable({items}){if(!items.length)return <div className="empty"><h3>نتیجه‌ای پیدا نشد</h3><p>منبع داده یا عبارت جستجو را بررسی کن.</p></div>;return <div className="mentions">{items.map((m,i)=>{const s=sentimentOf(m),t=topicOf(m);return <article key={m.link||i}><div className="mention-meta"><span>{m.platform||'Web'}</span><i className={s}>{s}</i><time>{m.published?new Date(m.published).toLocaleDateString('fa-IR'):''}</time></div><strong>{m.title||'بدون عنوان'}</strong><p>{m.source||'منبع نامشخص'}{m.link&&<a href={m.link} target="_blank" rel="noreferrer" style={{marginRight:10,color:'#aeb5c0'}}>مشاهده</a>}</p><footer><b>{t}</b><span>{m.relevance!=null?`Relevance ${m.relevance}`:''}</span></footer></article>})}</div>}
function Stats({items}){const counts={مثبت:0,منفی:0,خنثی:0};items.forEach(m=>counts[sentimentOf(m)]++);return <section className="stats"><div className="stat"><MessageCircle size={18}/><small>کل نتایج</small><strong>{items.length}</strong></div><div className="stat"><Activity size={18}/><small>مثبت / خنثی / منفی</small><strong>{counts.مثبت} / {counts.خنثی} / {counts.منفی}</strong></div><div className="stat"><Hash size={18}/><small>تاپیک‌ها</small><strong>{new Set(items.map(topicOf)).size}</strong></div><div className="stat"><Bell size={18}/><small>منابع</small><strong>{new Set(items.map(x=>x.platform||x.source)).size}</strong></div></section>}
export default function App(){const[page,setPage]=useState('overview'),[query,setQuery]=useState(''),[keyword,setKeyword]=useState(''),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState('');async function search(){const q=query.trim();if(!q)return;setLoading(true);setError('');try{const r=await fetch(`/api/search?q=${encodeURIComponent(q)}`),d=await r.json();if(!r.ok)throw Error(d.error||'Search failed');setItems(d.items||[]);setKeyword(q);setPage('feed')}catch(e){setItems([]);setError(e.message)}finally{setLoading(false)}}function csv(){const rows=[['Title','Platform','Sentiment','Topic','Source','Published','Link'],...items.map(m=>[m.title,m.platform,sentimentOf(m),topicOf(m),m.source,m.published,m.link])];const text=rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download=`listening-${keyword}.csv`;a.click()}const title=nav.find(x=>x[0]===page)?.[1]||'نمای کلی';return <div className="app" dir="rtl"><aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><b>Social Listening</b><small>UNIVERSAL MVP</small></div></div><button className="new-monitor" onClick={()=>{setQuery('');setKeyword('');setItems([]);setPage('overview')}}><Plus size={17}/> مانیتور جدید</button><nav>{nav.map(([id,l])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{l}</button>)}</nav></aside><main className="main"><header className="topbar"><div><small>SOCIAL LISTENING OS</small><h1>{title}</h1></div><div className="monitor-pill">{keyword||'بدون مانیتور'}</div></header><section className="hero"><div><span className="live">LIVE MONITORING</span><h2>{keyword?`گفتگو درباره «${keyword}»`:'هر موضوعی را مانیتور کن'}</h2><p>هر عبارت، برند، شخص، کمپین یا هشتگ را جستجو کن.</p></div></section><section className="search-box"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="مثلاً صحنه، مبین خودرو، نوبیتکس، یک کمپین..."/><button onClick={search} disabled={loading}>{loading?'در حال جستجو...':'جستجو'}</button></section>{error&&<div className="error">{error}</div>}{keyword&&<Stats items={items}/>}<section className="panel"><div className="head"><div><h3>{keyword?'فید نتایج':'آخرین نتایج'}</h3><small>{keyword?`${items.length} نتیجه برای «${keyword}»`:'برای شروع یک موضوع جستجو کن'}</small></div><div style={{display:'flex',gap:8}}>{keyword&&<button className="export" onClick={csv}><Download size={15}/> CSV</button>}<button className="export"><Filter size={15}/> فیلتر</button></div></div>{keyword?<ResultTable items={items}/>:<div className="empty"><h3>مانیتور جدید بساز</h3><p>عبارت موردنظر را وارد کن تا تیتر، پلتفرم، حس و تاپیک هر نتیجه را در یک فید واحد ببینی.</p></div>}</section></main></div>}
