import {resolveEntity,entitySearchTerms} from '../lib/entities.js';
const clean=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<!\[CDATA\[|\]\]>/g,'').replace(/\s+/g,' ').trim();
const normalize=s=>String(s||'').toLocaleLowerCase('fa-IR').replace(/[\u200c\u200d]/g,' ').replace(/[إأآ]/g,'ا').replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim();
const tokens=s=>normalize(s).replace(/[^\p{L}\p{N}#_-]/gu,' ').split(/\s+/).filter(Boolean);
const stop=new Set(['برای','درباره','این','آن','است','شد','شود','کرد','که','با','از','به','در','و','را','یک','های','خبر','گزارش','می','شده','کرده','the','and','for','with','from']);
const domain=url=>{try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}};
const platformOf=url=>{const h=domain(url);if(h==='instagram.com'||h.endsWith('.instagram.com'))return'Instagram';if(h==='t.me'||h==='telegram.me'||h.endsWith('.telegram.me'))return'Telegram';if(h==='youtube.com'||h.endsWith('.youtube.com')||h==='youtu.be')return'YouTube';if(h==='x.com'||h.endsWith('.x.com')||h==='twitter.com'||h.endsWith('.twitter.com'))return'X';return'Web'};
const allowed=(url,p)=>{const h=domain(url);if(p==='Instagram')return h==='instagram.com'||h.endsWith('.instagram.com');if(p==='Telegram')return h==='t.me'||h==='telegram.me'||h.endsWith('.telegram.me');if(p==='YouTube')return h==='youtube.com'||h.endsWith('.youtube.com')||h==='youtu.be';if(p==='X')return h==='x.com'||h.endsWith('.x.com')||h==='twitter.com';return !!h&&!/google\.|gstatic\.|bing\.com$|news\.google\.com$/.test(h)};
const parseRSS=xml=>[...String(xml||'').matchAll(/<item>([\s\S]*?)<\/item>/g)].map(m=>{const x=m[1],get=t=>clean(x.match(new RegExp(`<${t}(?:\\s[^>]*)?>([\\s\S]*?)<\\/${t}>`))?.[1]||'');return{title:get('title'),link:get('link'),published:get('pubDate')||get('published'),source:get('source'),description:get('description')};}).filter(x=>x.title&&x.link);
async function rss(url){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/rss+xml, application/xml, text/xml'},signal:AbortSignal.timeout(7000)});if(!r.ok)return[];return parseRSS(await r.text())}catch{return[]}}
async function news(q){return rss(`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=fa&gl=IR&ceid=IR:fa`)}
function parseMarkdownLinks(text){const out=[];for(const m of String(text||'').matchAll(/\[([^\]]{2,300})\]\((https?:\/\/[^)]+)\)/g)){const title=clean(m[1]),link=m[2];if(title&&link&&!/google\.com|gstatic\.com|accounts\.google/.test(link))out.push({title,link,source:domain(link),description:'',published:''})}return out}
async function googleWeb(q){try{const r=await fetch(`https://r.jina.ai/http://www.google.com/search?q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/plain'},signal:AbortSignal.timeout(9000)});if(r.ok){const rows=parseMarkdownLinks(await r.text());if(rows.length)return rows}}catch{}try{const r=await fetch(`https://r.jina.ai/http://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/plain'},signal:AbortSignal.timeout(9000)});if(!r.ok)return[];const text=await r.text(),out=[];for(const m of text.matchAll(/<a[^>]+class="result__a"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi)){const link=clean(m[1]),title=clean(m[2]);if(title&&link&&/^https?:\/\//.test(link))out.push({title,link,source:domain(link),description:'',published:''})}return out}catch{return[]}}
async function sourceSearch(term,p){const site=p==='Instagram'?'site:instagram.com':p==='Telegram'?'site:t.me OR site:telegram.me':p==='YouTube'?'site:youtube.com OR site:youtu.be':p==='X'?'site:x.com OR site:twitter.com':'';if(!site)return[];return(await googleWeb(`${site} ${term}`)).filter(x=>allowed(x.link,p)).map(x=>({...x,platform:p,searchTerm:term}))}
async function webSearch(term){return(await googleWeb(`"${term}"`)).filter(x=>allowed(x.link,'Web')).map(x=>({...x,platform:'Web',searchTerm:term}))}
const positive=/عالی|موفق|رشد|برنده|مثبت|بهترین|جذاب|محبوب|پیشرفت|موفقیت|رضایت|رکورد/;
const negative=/بد|بحران|شکست|انتقاد|حاشیه|منفی|کاهش|مشکل|اعتراض|اتهام|جنجال|نارضایتی|رسوایی/;
const sentiment=text=>{const n=normalize(text),pos=(n.match(new RegExp(positive.source,'g'))||[]).length,neg=(n.match(new RegExp(negative.source,'g'))||[]).length;return pos>neg?'مثبت':neg>pos?'منفی':'خنثی'};
const topic=(text,q)=>{const qn=normalize(q),words=tokens(text).filter(w=>w.length>3&&!stop.has(w)&&w!==qn);return[...new Set(words)].slice(0,3).join(' ')||q};
function classify(item,entity){const corpus=normalize(`${item.title||''} ${item.description||''}`),terms=entitySearchTerms(entity).map(normalize).filter(Boolean),primary=normalize(entity.name),matched=terms.filter(t=>corpus.includes(t)),primaryMatch=corpus.includes(primary),title=normalize(item.title||''),titleMatch=terms.some(t=>title.includes(t)),score=primaryMatch?100:titleMatch?90:matched.length?70:0;return{...item,relevance:score,isRelevant:score>=70,matchedEntities:matched,sentiment:sentiment(`${item.title} ${item.description||''}`),topic:topic(`${item.title} ${item.description||''}`,entity.name),usageType:['Web','News'].includes(item.platform)?'News Coverage':'Social Mention'}}
export default async function handler(req,res){const q=String(req.query?.q||'').trim();if(!q)return res.status(400).json({error:'Missing q'});try{const entity=resolveEntity(q),terms=entitySearchTerms(entity);const [webRows,newsRows,...social]=await Promise.all([Promise.all(terms.map(webSearch)).then(a=>a.flat()),Promise.all(terms.map(news)).then(a=>a.flat()),...['Instagram','Telegram','YouTube','X'].map(p=>Promise.all(terms.map(t=>sourceSearch(t,p))).then(a=>a.flat()))]);const input=[...webRows,...newsRows.map(r=>({...r,platform:'News'})),...social.flat()];const map=new Map();for(const item of input){const p=item.platform==='News'?'News':platformOf(item.link);if(item.platform!=='News'&&!['Instagram','Telegram','YouTube','X','Web'].includes(p))continue;const key=(item.link||'').split('#')[0].replace(/\/$/,'');if(key&&!map.has(key))map.set(key,{...item,platform:item.platform==='News'?'News':p});}const all=[...map.values()].map(x=>classify(x,entity));const relevant=all.filter(x=>x.isRelevant).sort((a,b)=>b.relevance-a.relevance).slice(0,100);const platforms={Instagram:0,Telegram:0,X:0,Web:0,YouTube:0,News:0};relevant.forEach(x=>platforms[x.platform]++);return res.status(200).json({query:q,entity,searchTerms:terms,count:relevant.length,rawCount:all.length,items:relevant,platforms,providers:{web:'google-index+duckduckgo-fallback',news:'google-news-rss',instagram:'public-index',telegram:'public-index',youtube:'public-index',x:'public-index'},diagnostics:{providers:[{name:'web',raw:webRows.length},{name:'news',raw:newsRows.length},{name:'instagram',raw:social[0]?.length||0},{name:'telegram',raw:social[1]?.length||0},{name:'youtube',raw:social[2]?.length||0},{name:'x',raw:social[3]?.length||0}],matched:relevant.length}})}catch(e){return res.status(502).json({error:e.message||'Search providers unavailable',items:[]})}}
