const clean=s=>(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<!\[CDATA\[|\]\]>/g,'').replace(/\s+/g,' ').trim();
const parseRSS=xml=>[...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(m=>{const x=m[1],get=t=>clean(x.match(new RegExp(`<${t}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${t}>`))?.[1]||'');return{title:get('title'),link:get('link'),published:get('pubDate')||get('published'),source:get('source'),platform:'News'};}).filter(x=>x.title);
async function rss(url,platform){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/rss+xml, application/xml, text/xml'}});if(!r.ok)return[];return parseRSS(await r.text()).map(x=>({...x,platform}));}catch{return[]}}
async function googleNews(query){return rss(`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=fa&gl=IR&ceid=IR:fa`,'Google News')}
async function bingNews(query){return rss(`https://www.bing.com/news/search?q=${encodeURIComponent(query)}&format=rss&setlang=fa-ir`,'Bing News')}
async function webSearch(query){try{const r=await fetch(`https://r.jina.ai/http://www.google.com/search?q=${encodeURIComponent(query)}`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)return[];const text=await r.text(),out=[];for(const m of text.matchAll(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g)){const title=clean(m[1]),link=m[2];if(title&&link&&!/google\.com/.test(link))out.push({title,link,source:new URL(link).hostname.replace(/^www\./,''),platform:'Web'});}return out.slice(0,20);}catch{return[]}}
const positive=/عالی|موفق|رشد|برنده|مثبت|بهترین|جذاب|محبوب|پیشرفت|موفقیت|رضایت/;
const negative=/بد|بحران|شکست|انتقاد|حاشیه|منفی|کاهش|مشکل|اعتراض|اتهام|جنجال|نارضایتی/;
const sentiment=text=>positive.test(text)?'مثبت':negative.test(text)?'منفی':'خنثی';
const topic=(text,q)=>{const words=text.replace(/[^\p{L}\p{N}#_-]/gu,' ').split(/\s+/).filter(Boolean);const stop=new Set(['برای','درباره','این','آن','است','شد','شود','کرد','که','با','از','به','در','و','را','یک','های','خبر','گزارش','می','شود','کرده']);return words.filter(w=>w.length>3&&!stop.has(w)&&w.toLowerCase()!==q.toLowerCase()).slice(0,3).join(' ')||q};
function classify(item,q){const text=`${item.title||''} ${item.source||''}`.toLowerCase(),qq=q.toLowerCase();const exact=text.includes(qq);const parts=qq.split(/\s+/).filter(Boolean);const partial=parts.length>1&&parts.every(w=>text.includes(w));const score=exact?100:partial?70:0;return{...item,relevance:score,isRelevant:score>=70,matchedEntities:score?[q]:[],sentiment:sentiment(item.title||''),topic:topic(item.title||'',q)}}
export default async function handler(req,res){const q=String(req.query?.q||'').trim();if(!q)return res.status(400).json({error:'Missing q'});const queries=[q,`"${q}"`,`"${q}" خبر`,`"${q}" برنامه`];try{const batches=await Promise.all(queries.map(async x=>[...(await googleNews(x)),...(await bingNews(x)),...(await webSearch(x))]));const map=new Map();for(const item of batches.flat()){const key=item.link||`${item.title}|${item.source}`;if(item.title&&!map.has(key))map.set(key,item);}const all=[...map.values()].map(x=>classify(x,q));const relevant=all.filter(x=>x.isRelevant).sort((a,b)=>b.relevance-a.relevance).slice(0,50);return res.status(200).json({query:q,count:relevant.length,items:relevant,rawCount:all.length,providers:{googleNews:true,bingNews:true,web:true}});}catch(e){return res.status(502).json({error:e.message||'Search provider unavailable'});}}
