const clean=s=>(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<!\[CDATA\[|\]\]>/g,'').replace(/\s+/g,' ').trim();
const parseRSS=xml=>[...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(m=>{const x=m[1],get=t=>clean(x.match(new RegExp(`<${t}>([\\s\\S]*?)<\\/${t}>`))?.[1]||'');return{title:get('title'),link:get('link'),published:get('pubDate'),source:get('source'),platform:'Web / News'};}).filter(x=>x.title);
async function googleNews(query){try{const r=await fetch(`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=fa&gl=IR&ceid=IR:fa`,{headers:{'User-Agent':'Mozilla/5.0'}});return r.ok?parseRSS(await r.text()):[];}catch{return[]}}
async function bing(query){try{const r=await fetch(`https://www.bing.com/search?q=${encodeURIComponent(query)}&setlang=fa-ir&count=20`,{headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'fa-IR,fa;q=0.9'}});if(!r.ok)return[];const html=await r.text(),out=[];for(const m of html.matchAll(/<li class="b_algo"[\s\S]*?<h2><a href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g)){const link=m[1],title=clean(m[2]);if(!title)continue;let source='Web';try{source=new URL(link).hostname.replace(/^www\./,'')}catch{}out.push({title,link,source,platform:/t\.me|telegram/i.test(link)?'Telegram':'Web'});}return out;}catch{return[]}}
const positive=/عالی|موفق|رشد|برنده|مثبت|بهترین|جذاب|محبوب|پیشرفت|موفقیت|رضایت/;
const negative=/بد|بحران|شکست|انتقاد|حاشیه|منفی|کاهش|مشکل|اعتراض|اتهام|جنجال|نارضایتی/;
const sentiment=text=>positive.test(text)?'مثبت':negative.test(text)?'منفی':'خنثی';
const topic=(text,q)=>{const words=text.replace(/[^\p{L}\p{N}#_-]/gu,' ').split(/\s+/).filter(Boolean);const stop=new Set(['برای','درباره','این','آن','است','شد','شود','کرد','که','با','از','به','در','و','را','یک','های','خبر','گزارش','می','شود','کرده']);return words.filter(w=>w.length>3&&!stop.has(w)&&w.toLowerCase()!==q.toLowerCase()).slice(0,3).join(' ')||q};
function classify(item,q){const text=`${item.title} ${item.source}`.toLowerCase(),qq=q.toLowerCase();const exact=text.includes(qq);const wordParts=qq.split(/\s+/).filter(Boolean);const partial=wordParts.length>1&&wordParts.every(w=>text.includes(w));let score=exact?90:partial?65:0;return{relevance:score,isRelevant:score>=65,matchedEntities:score?[q]:[],excludedTerms:[],sentiment:sentiment(item.title||''),topic:topic(item.title||'',q)}}
export default async function handler(req,res){const q=String(req.query?.q||'').trim();if(!q)return res.status(400).json({error:'Missing q'});const queries=[q,`"${q}"`,`"${q}" خبر`,`"${q}" برنامه`];try{const batches=await Promise.all(queries.map(async x=>[...(await googleNews(x)),...(await bing(x))]));const map=new Map();for(const item of batches.flat()){const key=item.link||`${item.title}|${item.source}`;if(item.title&&!map.has(key))map.set(key,item);}const classified=[...map.values()].map(item=>({...item,...classify(item,q),query:q}));const relevant=classified.filter(x=>x.isRelevant).sort((a,b)=>b.relevance-a.relevance).slice(0,50);return res.status(200).json({query:q,count:relevant.length,items:relevant,rawCount:classified.length});}catch(e){return res.status(502).json({error:e.message||'Search provider unavailable'});}}
